image: alpine

before_script:
  - apk add curl

stages:
  - build
  - deploy

build:
  stage: build
  script: curl https://checkip.amazonaws.com

deploy:
  stage: deploy
  script: curl https://checkip.amazonaws.com
