# .gitlab-ci.yml

image: node:16

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules
    - .yarn-cache

job:
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
