job:
  script:
    - echo $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.dev.corp.com
    - echo docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    - echo docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
