# .gitlab-ci.yml

image: sikalabs/ci

stages:
  - build

build:
  stage: build
  script:
    - infracost breakdown --path . --format json --out-file infracost.local.out.json
    - infracost output --path infracost.local.out.json --format html --out-file infracost.local.out.html
  artifacts:
    paths:
      - out

