# .gitlab-ci.yml

variables:
  HOST: $CI_COMMIT_REF_SLUG.k8s.sikademo.com

deploy:
  script: 
    - helm upgrade --install $CI_COMMIT_REF_SLUG hello-world --repo https://helm.sikalabs.io --set host=$HOST
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$HOST
    on_stop: stop deploy

stop deploy:
  variables:
    GIT_STRATEGY: none
  script: helm uninstall $CI_COMMIT_REF_SLUG
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
